<?php

return
   [
      'api_url' => env('RAJAONGKIR_API_URL', 'https://api.rajaongkir.com/starter/'),
      'api_url_basic' => env('RAJAONGKIR_API_BASIC_URL', 'https://api.rajaongkir.com/basic/'),
      'api_url_pro' => env('RAJAONGKIR_API_PRO_URL', 'https://pro.rajaongkir.com/api/'),
      'api_pro_token' => env('RAJAONGKIR_PRO_TOKEN'),
      'courier_starter' =>
      [
         ['label' => 'JNE', 'value' => 'jne'],
         ['label' => 'TIKI', 'value' => 'tiki'],
         ['label' => 'POS', 'value' => 'pos'],
      ],
      'courier_basic' =>
      [
         ['label' => 'JNE', 'value' => 'jne'],
         ['label' => 'TIKI', 'value' => 'tiki'],
         ['label' => 'POS', 'value' => 'pos'],
         ['label' => 'PCP Express', 'value' => 'pcp'],
         ['label' => 'RPX Holding', 'value' => 'rpx'],
      ],
      'courier_pro' =>
      [
         ['label' => 'JNE', 'value' => 'jne'],
         ['label' => 'TIKI', 'value' => 'tiki'],
         ['label' => 'POS', 'value' => 'pos'],
         ['label' => 'PCP Express', 'value' => 'pcp'],
         ['label' => 'RPX Holding', 'value' => 'rpx'],
         ['label' => 'JNT Express', 'value' =>  'jnt'],
         ['label' => 'Wahana', 'value' =>  'wahana'],
         ['label' => 'IDE (ID Express)', 'value' =>  'ide'],
         ['label' => 'Ninja Xpress', 'value' =>  'ninja'],
         ['label' => 'SICEPAT Express', 'value' =>  'sicepat'],
         ['label' => 'ANTERAJA', 'value' =>  'anteraja'],
         ['label' => 'SAP', 'value' =>  'sap'],
         ['label' => 'REX (Royal Express Indonesia)', 'value' =>  'rex'],
         ['label' => 'PANDU Logistics', 'value' =>  'pandu'],
         ['label' => 'FIRST Logistics', 'value' =>  'first'],
         ['label' => 'SENTRAL Cargo', 'value' =>  'sentral'],
         ['label' => 'SLIS (Solusi Express)', 'value' =>  'slis'],
         ['label' => 'NCS (Nusantara Card Semesta)', 'value' =>  'ncs'],
         ['label' => 'DSE (21 Express)', 'value' =>  'dse'],
         ['label' => 'IDL Cargo', 'value' =>  'idl'],
         ['label' => 'JTL Express', 'value' =>  'jtl'],
      ],
      'tracking_supports' => [
         'pos',
         'lion',
         'ninja',
         'ide',
         'sicepat',
         'sap',
         'ncs',
         'anteraja',
         'rex',
         'jtl',
         'sentral',
         'wahana',
         'jnt',
         'ray',
         'first',
         'star',
         'idl',
      ],
   ];
